// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBasYoFsF2ZbUUb6MPLaylcKZcefzK3Al8',
    appId: '1:781081346824:web:51527c742a798ab80c62bd',
    messagingSenderId: '781081346824',
    projectId: 'projetoglossario',
    authDomain: 'projetoglossario.firebaseapp.com',
    storageBucket: 'projetoglossario.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Ya1G6Zq4WpoKEgGsoengMb4bWbmO64M',
    appId: '1:781081346824:android:e28679c3736c01110c62bd',
    messagingSenderId: '781081346824',
    projectId: 'projetoglossario',
    storageBucket: 'projetoglossario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA4nrMYfFGyFA7yFZWSuphfhUqoD8a0vI',
    appId: '1:781081346824:ios:d46cfe346b3d03140c62bd',
    messagingSenderId: '781081346824',
    projectId: 'projetoglossario',
    storageBucket: 'projetoglossario.appspot.com',
    iosBundleId: 'com.example.glossario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA4nrMYfFGyFA7yFZWSuphfhUqoD8a0vI',
    appId: '1:781081346824:ios:d46cfe346b3d03140c62bd',
    messagingSenderId: '781081346824',
    projectId: 'projetoglossario',
    storageBucket: 'projetoglossario.appspot.com',
    iosBundleId: 'com.example.glossario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBasYoFsF2ZbUUb6MPLaylcKZcefzK3Al8',
    appId: '1:781081346824:web:3332e2acbfa1fe430c62bd',
    messagingSenderId: '781081346824',
    projectId: 'projetoglossario',
    authDomain: 'projetoglossario.firebaseapp.com',
    storageBucket: 'projetoglossario.appspot.com',
  );
}
